# Generated by Django 5.0.9 on 2025-01-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_trigram_ext'),
    ]

    operations = [
    ]
